DD-19300 DD-18856 Squashed commit of the following:
commit 3bdaeb3257c89958c397e0ad07c5e247c3ddbc47
Merge: 5592d471dd 7c7dabd394
Author: Arcadius Ahouansou <arcadius@menelic.com>
Date:   Sun Mar 13 03:48:15 2022 +0000

    Merge branch 'master' into team/cpssearch

    Change-Id: Ib5c6989cb4aa5e61c9d3a1af14e81ba2b31383f7

commit 5592d471dd3db7bbf13110a12fc0a97b5fe219e9
Author: Arcadius Ahouansou <arcadius@menelic.com>
Date:   Fri Mar 11 19:00:22 2022 +0000

    DD-18856 DD-19828 Progression: Old duplicate RR from eventstore to be removed from Aggregate

    Change-Id: Ie871003fd2ef479e1ac5bb340c686b06d6d002a1

commit c42764bbf5358106ffc2fd7a45d935928fea360c
Author: vijay.dabas <vijay.dabas@hmcts.net>
Date:   Fri Mar 11 15:25:24 2022 +0000

    Updated for dup offences

    Change-Id: I595ba123e25be5180b9e66b32bc6afe1c4bd3ef9

commit 5601bf15d121994b3a2fb8ec5f9c6fa3df0c63c1
Author: Arcadius Ahouansou <arcadius@menelic.com>
Date:   Fri Mar 11 03:27:48 2022 +0000

    DD-18856 DD-19304 Duplicate ReportingRestrictions in viewstore for progression: group by judicialResultId

    Change-Id: I352fee08b37ecf2245465f3535757412e7dca5ba

commit 30ac04afd650816f1c52b2faf7607ef740c3af59
Author: Arcadius Ahouansou <arcadius@menelic.com>
Date:   Thu Mar 10 21:50:18 2022 +0000

    DD-18856 DD-19304 Duplicate ReportingRestrictions in viewstore for progression: Fixing java.lang.NoSuchMethodError: uk.gov.justice.core.courts.DefendantCaseOffences$Builder.withValuesFrom(Luk/gov/justice/core/courts/DefendantCaseOffences;)

    Change-Id: I9b92e5557532c1af6c31160a30961d25b798f03c

commit 9baaf08116676a977101bd66c984824a4b5aa904
Author: vijay.dabas <vijay.dabas@hmcts.net>
Date:   Thu Mar 10 17:06:02 2022 +0000

    De dup offences changes

    Change-Id: I8310df5aee436409d35dec87de971f2a8e1c51ed

commit 214c5777755fc6f81b2611c6d9c6f1e33d8bc486
Merge: c588b434d1 de809c6044
Author: Arcadius Ahouansou <arcadius@menelic.com>
Date:   Thu Mar 10 14:41:05 2022 +0000

    Merge branch 'master' into team/cpssearch

    Change-Id: Ic7069462bd4a54aeeb12d0d861b8cf813723c7f6

commit c588b434d195798b8871408471c3da56beb003c4
Author: Arcadius Ahouansou <arcadius@menelic.com>
Date:   Thu Mar 10 11:35:54 2022 +0000

    DD-18856 DD-19304 Duplicate ReportingRestrictions in viewstore for progression

    Change-Id: I660851ddb85164361c7e55b198f3cbed70c55628

commit 901e10b15251ce4fbec47be1ce31de5daa3e5ef3
Author: vijay.dabas <vijay.dabas@hmcts.net>
Date:   Thu Mar 10 10:59:26 2022 +0000

    duplicate offence fix

    Change-Id: I9bd92a151784a4c51ca2f310c1c94960fd2ddddf

commit 64afdf091a033fc5805a2cb1447bc9f31d5c6657
Author: Arcadius Ahouansou <arcadius@menelic.com>
Date:   Thu Mar 10 10:24:09 2022 +0000

    NA: pom update

    Change-Id: I2194c1065ab67fed36e477fb734f7a6da0307405

Change-Id: If3f511eea3c85209a08f2ec58a629b556deba11f